# Generated by Django 4.1 on 2022-08-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminInfo',
            new_name='TodoLists',
        ),
    ]
