# Generated by Django 4.1 on 2022-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_admininfo_todolists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolists',
            name='details',
        ),
        migrations.RemoveField(
            model_name='todolists',
            name='name',
        ),
        migrations.AddField(
            model_name='todolists',
            name='priority',
            field=models.CharField(choices=[('1', 'Important & Urgent'), ('2', 'Important & Not Urgent'), ('3', 'Not Important & Urgent'), ('4', 'Not Important & Not Urgent')], default=1, max_length=4),
        ),
    ]
