# Generated by Django 4.1 on 2022-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_todolists_details_remove_todolists_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='category',
            field=models.CharField(choices=[('1', 'Money'), ('2', 'Language'), ('3', 'Habit'), ('4', 'Job'), ('5', 'Life Style')], default=1, max_length=20),
        ),
    ]
