# Generated by Django 4.1 on 2022-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_todolists_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='title',
            field=models.CharField(default='Core', max_length=200),
        ),
    ]
